### ISSUE TITLE
Julia process pins CPU at 100% after vim is closed

### ISSUE THREAD

**Issue by Moelf** [kdheepak/JuliaFormatter.vim#27] opened 2021-06-14 18:57 UTC
### Troubleshooting
```
akako@ThinkX ~/D/g/Julia (fix_search_last)> vim --version
NVIM v0.5.0-dev+1386-gfd7e77b22
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az68-784

Features: +acl +iconv +tui
See ":help feature-compile"

julia --project=~/.vim/plugged/JuliaFormatter.vim/ -e "using Pkg; Pkg.status()"
      Status `~/.vim/plugged/JuliaFormatter.vim/Project.toml`
  [682c06a0] JSON v0.21.1
  [98e50ef6] JuliaFormatter v0.14.4
  [9b87118b] PackageCompiler v1.2.5

julia --project=~/.vim/plugged/JuliaFormatter.vim/ -e "using InteractiveUtils; versioninfo()"
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by kdheepak** [comment] 2021-06-14 20:47
That’s odd. I’ll look into it.

**Comment by kdheepak** [comment] 2021-06-24 19:25
I added a `kill` using `autocmd` on `VimLeave`. Can you try this and let me know if you are still having issues?

**Comment by adigitoleo** [comment] 2021-06-25 14:32
I just realised that an error was flicking up before closing (n)vim after I installed this plugin. Looks like it's related to this.

From the log:
```
Error detected while processing function JuliaFormatter#Kill:
line    2:
E121: Undefined variable: s:job
E15: Invalid expression: s:job>0
```

**Comment by kdheepak** [comment] 2021-06-25 14:40
Huh, strange that I’m not getting any error!

**Comment by kdheepak** [comment] 2021-06-25 14:40
@adigitoleo presumably you are using nvim? So am I.

**Comment by adigitoleo** [comment] 2021-06-25 15:13
Yep, neovim 0.4 (not nightly). If you can't repro I'm happy to investigate further, I've just been messing around with my vimrc again so I'll try to repro with a minimal setup.

**Comment by kdheepak** [comment] 2021-06-25 15:28
Can you try it again now? I added spaces around the operator: https://github.com/kdheepak/JuliaFormatter.vim/commit/5ee95b31a2124a03071f00074ce4ff0c8aa4b9e1 

If that doesn't work, can you try PR #31? 

There's a MINRC file in the `tests` folder here: https://github.com/kdheepak/JuliaFormatter.vim/blob/5ee95b31a2124a03071f00074ce4ff0c8aa4b9e1/tests/MINRC

You can run `vim -u tests/MINRC tests/test.jl` to see if you can reproduce this.

**Comment by adigitoleo** [comment] 2021-06-25 15:43
Probably not this plugin, can't repro with the minimal setup. maybe julia.vim or my LSP plugin is doing some weird stuff. I might have to pick this up tomorrow, but I'll let you know if I find anything.

**Comment by adigitoleo** [comment] 2021-06-25 16:07
My issue doesn't seem to be the same, I don't see CPU spikes, so I'm moving it to a new issue (#32).

**Closed** 2021-06-25 16:46 UTC
